name: Changeset Versioning PR
run-name: Changeset Versioning PR

on:
  push:
    branches:
      - main # Trigger on push to main branch

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  version-pr:
    name: Create Versioning PR
    runs-on: 'ubuntu-latest'
    timeout-minutes: 10

    permissions:
      contents: write
      id-token: write
      packages: write
      pull-requests: write
      issues: read
      statuses: write
      checks: write

    steps:
      - name: Echo github context
        run: echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}

      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          show-progress: false

      - name: Install PNPM
        uses: pnpm/action-setup@v4

      - name: Setup NodeJS 20
        uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version: '20'
          registry-url: https://registry.npmjs.org

      - name: Install PNPM Dependencies
        env:
          CYPRESS_INSTALL_BINARY: 0
        run: pnpm install
        shell: bash

      - name: Build release
        run: pnpm turbo build $TURBO_ARGS --force

      - name: Create Release PR
        id: changesets
        uses: changesets/action@v1
        with:
          commit: 'ci(repo): Version packages'
          title: 'ci(repo): Version packages'
          publish: pnpm release
          # Workaround for https://github.com/changesets/changesets/issues/421
          version: pnpm version-packages
        env:
          GITHUB_TOKEN: ${{ secrets.CHANGESETS_GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_CONFIG_PROVENANCE: true

      - name: Discord Notification
        id: notification
        if: steps.changesets.outputs.published == 'true'
        uses: Ilshidur/action-discord@master
        with:
          args: "🎉 A new release has been published! Check out the latest changes in the releases tab 🚀"
        env:
          DISCORD_WEBHOOK : ${{ secrets.CHANGESETS_DISCORD_WEBHOOK }}